### ISSUE TITLE
Crashing at launch

### ISSUE THREAD

**Issue by Tsagu** [payday-restoration/restoration-mod#109]
Tue Aug 20 11:07:24 2019

Application has crashed: C++ exception
[File] Cannot read from file "F:\Steam Library\steamapps\common\PAYDAY 2\mods/restoration-mod-gold/assets/units/pd2_mod_nypd/characters/ene_spook_1/ene_spook_classic_body_df.texture" => error code 998: Invalid access to memory location. (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs\../utility/Archive.cpp:2470)

SCRIPT_STACK

load() lib/managers/dynamicresourcemanager.lua:151
_LoadAsset() 189
update() 212
func() @mods/BeardLib/Core.lua:155
Call() @mods/base/req/core/Hooks.lua:109
update() @mods/base/lua/MenuSetup.lua:7
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  189                                                 
                      update()  212                                                 
                        func()  @mods/BeardLib/Core.lua:155                         
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                      update()  @mods/base/lua/MenuSetup.lua:7                      
                                core/lib/setups/coresetup.lua:540                   

-------------------------------

System information:
	Application version : 1.92.790
	CPU : AMD FX(tm)-6350 Six-Core Processor (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[26.21.14.3160]
	Language : english
	Memory :     8139MB 20KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Neslon-Poggers** [comment]
does this crash happen on the dev build?
