### ISSUE TITLE
dlcmanager crash

### ISSUE THREAD

**Issue by EvilBobarino** [payday-restoration/restoration-mod#122]
Application has crashed: C++ exception
[string "lib/managers/dlcmanager.lua"]:258: attempt to index local 'entry' (a nil value)

SCRIPT STACK

verify_dlc_items() lib/managers/blackmarketmanager.lua:7067
give_dlc_and_verify_blackmarket() lib/managers/dlcmanager.lua:162
func() lib/managers/dlcmanager.lua:176
dispatch() core/lib/utils/coreevent.lua:212
_on_load_sequence_complete() lib/managers/savefilemanager.lua:255
update() lib/managers/savefilemanager.lua:240
update() lib/setups/setup.lua:853
update() lib/setups/menusetup.lua:340
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     zip_get_name
         payday2_win32_release  (???)     zip_get_name

-------------------------------

Current thread: Main

-------------------------------

https://puu.sh/EfQQf/40035bb48e.png

**Comment by EvilBobarino** [comment]
"i took my base game save and made two copies, one for VR and another for Resmod, so all 3 saves should be most recent"

still crashing after attempted work around

**Comment by steam-test1** [comment]
Try the following mod
[Clean Blackmarket.zip](https://github.com/payday-restoration/restoration-mod/files/3612845/Clean.Blackmarket.zip)

Load the normal game
Set a keybind for the mod
Press in main menu
Enter inventory and then exit inventory
After the game has saved exit game
Then create saves for both VR and ResMod
Then load VR game

**Comment by EvilBobarino** [comment]
didnt seem to work h

**Comment by EvilBobarino** [comment]
happening for someone who didnt play the vr beta 
maybe linked to a weapon mod we made?
or a weapon slot change?

**Comment by steam-test1** [comment]
Try running the following with the same steps
[Clean DLC.zip](https://github.com/payday-restoration/restoration-mod/files/3636463/Clean.DLC.zip)
It should delete ResMod items from the save file

**Comment by EvilBobarino** [comment]
no luck

**Comment by EvilBobarino** [comment]
same crash happens on dev

**Comment by steam-test1** [comment]
Last try
[Fix global value.zip](https://github.com/payday-restoration/restoration-mod/files/3639840/Fix.global.value.zip)
This restores missing DLC items 

Load the normal game
Set a keybind for the mod
Press in main menu
After the game has saved exit game
Then create saves for both VR and ResMod
Then load VR game

**Comment by EvilBobarino** [comment]
nothing 

is it an issue with one of our custom mods or masks?

**Comment by EvilBobarino** [comment]
weapon mods*

**Comment by EvilBobarino** [comment]
based on what SenpaiKillerFire has been trying breaking dlctweakdata fixed this issue this has the side effect of not being able to buy mod specific items

at least we know whats causing this crash right???
