### ISSUE TITLE
bot stop ai button has bug.

### ISSUE THREAD

**Issue by bingo12345** [payday-restoration/restoration-mod#180]
Stop ai button is bugged.
When using Stop ai button, the bot can't turn around so the bot can't attack enemy behind of it.(the bot can only attack enemy within front view of him)
this occurs on restoration mod only. vanilla game bot doesn't have this bug.

when i tested this, stop ai button works well in vanilla. the bot can turn around and attack enemy behind of it in vanilla.

using stop ai button on a bot alone at some place is suicide button. the bot is stupidly hit by enemies behind of him until it dies.

**Comment by EssCee** [comment]
This was fixed some time ago, closing this issue.
