### ISSUE TITLE
CTD on customized Maps

### ISSUE THREAD

**Issue by nachoman87** [payday-restoration/restoration-mod#183]
Hi,

Im getting errors when i try to start a custom Map. (Ukranian Job, Firestarter)
First i tought that Libbeard was the reason but the crashes seems only to apear when the restoration mod is activated.
Activated Mods: Beard Lib, Restoration Mod, Voiceline Framework

Ive tried many things:
-Relocated(from HDD to SSD), redownloaded and reinstalled Game
-Redownload and install Mods
-made a fresh start with a new Savegame
-Deactivate unecessary Background Services
-Deactivate unecessary Background Tasks
-tried to locate the error with procmon (couldnt find anything suspicious)
-tried to find information in the mdmp data (also negative)

[log.txt](https://github.com/payday-restoration/restoration-mod/files/4678026/log.txt)
[short-log.txt](https://github.com/payday-restoration/restoration-mod/files/4678027/short-log.txt)
[crash.txt](https://github.com/payday-restoration/restoration-mod/files/4678028/crash.txt)
[data.txt](https://github.com/payday-restoration/restoration-mod/files/4678029/data.txt)

crash.txt:
```
Application has crashed: C++ exception
[string "core/lib/utils/dev/editor/coreworlddefinition..."]:249: attempt to index field 'world_data' (a nil value)


SCRIPT STACK

WorldDefinition_init() core/lib/utils/dev/editor/coreworlddefinition.lua:44
WorldDefinition_init() @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10
init() @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10
init() lib/utils/dev/editor/worlddefinition.lua:6
new() core/lib/utils/coreclass.lua:35
init() core/lib/utils/dev/editor/worldholder.lua:49
new() core/lib/utils/coreclass.lua:35
init_game() lib/setups/gamesetup.lua:653
core/lib/setups/coresetup.lua:422


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.94.887
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[26.21.14.4587]
	Language : english
	Memory :     32706MB 456KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (VoiceMeeter Input (VB-Audio VoiceMeeter VAIO))


```

**Comment by Ravicale** [comment]
We've seen this issue pop up occasionally in the Troubleshooting channel in our discord. As best we know, the game is having trouble opening the continents info in the heist. By any chance do you have a full mod list to share? The issue seems to hit some users but not others.

**Comment by nachoman87** [comment]
hi,
sure the full modlist is in data.txt 

the 3 maps are for test reason there.

data.txt
```
25 May 2020 17:32:55
::INSTALLED BLT MODS::

Name: Trouble Shooter                                                                                     Path: mods/TroubleShooter/
Name: SuperBLT                                                                                            Path: mods/base/
Name: BeardLib                                                                                            Path: mods/BeardLib/
Name: Voiceline Framework                                                                                 Path: mods/voiceline-framework-master/
Name: RestorationMod                                                                                      Path: mods/restoration-mod/


::INSTALLED BEARDLIB MODS::

NONE


::INSTALLED MAPS::

Name: Armsdeal Alleyway                                                                                   Path: Maps/Armsdeal Alleyway/
Name: Hardware Store v1.3                                                                                 Path: Maps/Hardware Store v1.3/
Name: Underground Bargains v1.3.1                                                                         Path: Maps/Underground Bargains v1.3.1/


::INSTALLED OVERRIDES::

NONE

```

**Comment by Ravicale** [comment]
I take it that the other custom heists did not crash at all?

**Comment by nachoman87** [comment]
they all crashed with mod.
Without the mod all of them are working fine.

**Comment by Ravicale** [comment]
Strange, we don't touch anything relating to how heists are loaded. Looked through old posts in both our public troubleshooting channel on discord and the bug_reports channel in the dev discord and found one other instance of the crash from 2019 (ignoring the one you posted), but it's from a user who hasn't gotten it since???

By some chance, see if you can load the heists in resmod with your textures set to very low. You can   increase texture quality again once in game. The engine can sometimes run into memory related issues while loading heists (32 bit is fun), though the crashlogs usually lack a callstack and/or contain Direct3d errors.

Either way, I'm at a bit of a loss here.

**Comment by nachoman87** [comment]
tried but no luck. 
I will make a fresh install of Windows, lets see.

**Comment by nachoman87** [comment]
ok, it seems that the crash only happens when i try to start a custom maps from the mod (Fire Starter, ukranian).
Missions from the Workshop working well.

**Comment by Ravicale** [comment]
Was a beardlib issue, fixed a few versions ago.
