### ISSUE TITLE
The game crashes on next start when closing it after going to the skills 

### ISSUE THREAD

**Issue by dpertierra** [payday-restoration/restoration-mod#199]
There's a popup error with the following message: "[WREN/WXML] XML new: parse error - see log for details"

![image](https://user-images.githubusercontent.com/17021695/99720361-6a2c2c80-2a8c-11eb-9d53-7279e55dc13b.png)

I see the following FATAL Erros in the mods log
* 02:26:44 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:51) CURL_INITD
* 02:26:46 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\tweaker\wrenloader.cpp:29) [WREN] XML-Tweaking Bundle File 4baacfbda800c3a1.5f4f63fc336a19d5
* 02:26:46 PM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\tweaker\wrenxml.cpp:92) Could not load XML: Error and original file below
* 02:26:46 PM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\tweaker\wrenxml.cpp:93) Bad control character 0x11 not allowed by XML standard!
* 02:26:46 PM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\tweaker\wrenxml.cpp:94) Input XML:
* 02:26:46 PM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\tweaker\wrenxml.cpp:95) <?xml version="1.0"?>
* 02:26:46 PM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\tweaker\wrenxml.cpp:98) [WREN/WXML] XML.new: parse error - see log for details

I have the following mods besides restoration installed
* AntiIntimidatedOutlines 
* BeardLib
* Coloured Loading Screens
* DEADLOCKE
* dont-waste-a-drop
* Drag and Drop Inventory
* Enhanced Hitmarkers
* Graze doesn't kill civils
* Hostage Pathing Fix
* Insta-pickup Gage Packages
* Intro Cinematics Standalone
* Joker Masks
* Lobby Mod Filter
* Mouse Wheel to Switch Weapons
* Not Again! Even More Skillsets! Anti-Infamy
* Oh Shit! More Profiles
* Reconnect to server
* use-ability-while-shooting-or-driving
* VanillaHUD Plus

**Comment by EvilBobarino** [comment]
This is an issue with SuperBLT.  There's nothing anyone can do -- simply restart your game until it works fine.

**Comment by EssCee** [comment]
As it was said, XML parsing errors are a bug stemming from custom animations on newer versions of SuperBLT. Usually a restart or two will remedy this issue, and unfortunately there is nothing we can do to fix it.
