### ISSUE TITLE
Hud/Menu U186 Hotfix

### ISSUE THREAD

**Issue by steam-test1** [payday-restoration/restoration-mod#20]
Changelog

Updated HUDAssaultCorner with Holdout support
Updated HUDMissionBriefing and MissionBriefingGUI with Holdout support

**Comment by EssCee** [comment]
That's pretty awesome, thanks for that!

**Comment by steam-test1** [comment]
Fixed version

The previous version had a bug that is now fixed

Bugs/Issues
The wave started popup doesn't show

https://github.com/steam-test1/restoration-mod/blob/dev/restoration%20holdout%20hotfix.zip?raw=true

**Comment by EssCee** [comment]
Funny you mention that, we were just talking about this too.

Thanks!
