### ISSUE TITLE
Game crashing on start

### ISSUE THREAD

**Issue by payday2123** [payday-restoration/restoration-mod#200]
Hi,
My Game's crashing on start.
Here is the crash.txt: https://pastebin.com/raw/w4vEf6Gj
I have BeardLib and SuperBLT installed, I also tried it with no other Mods, but still no luck.
I hope someone could help me.

**Comment by EvilBobarino** [comment]
do you have vanilla mod pack 1 or 2?

**Comment by payday2123** [comment]
Is that a requirement?

**Comment by Neslon-Poggers** [comment]
no

**Comment by Neslon-Poggers** [comment]
are you running a pirated copy by any chance?

**Comment by payday2123** [comment]
No

**Comment by payday2123** [comment]
Should I try to reinstall the game?

**Comment by Neslon-Poggers** [comment]
i guess

that crash indicates that the bernetti rangehitter from the gunslinger weapon pack doesn't exist

**Comment by payday2123** [comment]
Alright, maybe I or a mod accidently deleted something, I'll try to reinstall the game, thanks!
