### ISSUE TITLE
Pro-Job Option frequently does not activate on custom heists/levels

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#22]
Title is self-explanatory.  Even when ensured to be ticked on, a custom narrative/level will not start in Pro-Job mode.  Reason unknown.

**Comment by SOMNUSNOVUS** [comment]
Custom narratives seem to get stuck using the last-applied setting for Pro-Jobs.  If previous heist wasn't Pro, the custom narrative won't use it.  Must solve - partially gamebreaking (unable to get achievements for OD stuff in some situations)

**Comment by steam-test1** [comment]
I created a pull request for Beardlib which fixes this issue

**Comment by SOMNUSNOVUS** [comment]
Thank you.  Once Beardlib merges that PR, we'll close this issue.

**Comment by SOMNUSNOVUS** [comment]
Oh, they already merged it!  Issue resolved.
