### ISSUE TITLE
Shadow text animation non-functional on most screens outside of loadouts

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#24]
I forget which update caused this tiny issue in particular, but the file MenuBackdropGUI (_lua/managers/menu/MenuBackdropGUI.lua_) no longer functions properly outside of the loadouts screen/other scattered instances.

Ideally, it should be working at all times (as it did in older versions of PD2), and animate all text drop-shadows properly.  Exact cause for it no to activate on main menus, loading screen, etc. unknown.

**Comment by steam-test1** [comment]
This has been fixed
