### ISSUE TITLE
S&W .500 Weapon Not Functional

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#25]
We tried to add a brand new weapon to the game -- the S&W .500, without using BeardLib (so that this would sync to other overhaul users & all overhaul users would have access to it), but despite all code looking correct, the weapon never showed in the in-game black market.

Weapon ID is 'jeb'.

**Comment by SOMNUSNOVUS** [comment]
Further research shows that the weapon data is never initialized, even though the init function & the call for it are present.  What gives?

**Comment by sonj2** [comment]
For future reference: when I tried to implement the S&W the same way as Sora did with Broken Arrow and the Zombie maps in general, the game crashes once reaching the first line related with the weapon in weapontweakdata.lua.

The specific line is: `self.jeb = deep_clone(self.new_raging_bull)` 
This is the following crash report:
```
Application has crashed: C++ exception
[string "lib/managers/upgradesmanager.lua"]:565: attempt to index local 'upgrade' (a nil value)

SCRIPT STACK

_setup_weapons() lib/managers/blackmarketmanager.lua:296
_setup() lib/managers/blackmarketmanager.lua:54
init() lib/managers/blackmarketmanager.lua:18
new() core/lib/utils/coreclass.lua:35
init_managers_original() lib/setups/setup.lua:382
original() @mods/WolfHUD-jimhud/lua/WaypointsManager.lua:93
init_managers() @mods/base/req/core/Hooks.lua:260
init_managers() lib/setups/menusetup.lua:273
coresetup_init_orig() core/lib/setups/coresetup.lua:382
@mods/The Fixes Preventer/coresetup.lua:7

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name
```

**Comment by SOMNUSNOVUS** [comment]
Is there any reason we're actually cloning raging bull?  It seems like the cause of this crash -- new_raging_bull still has upgrades attached to it from legacy code.

**Comment by sonj2** [comment]
From what I remember, the crash happens even if the clone target isn't the raging bull. I remember trying wa2000, chinchilla, glock_17, and even derringer which is a custom weapon. In Sora's work, all custom weapons were first cloned, then it was tweaked afterwards; I'm to believe its to fill in potentially any fields that were not filled out or to reduce the number of lines of code in general.

**Comment by sonj2** [comment]
This was when I specifically tried to do it the way Sora did for the maps

**Comment by SOMNUSNOVUS** [comment]
May need to avoid cloning and fill out every field manually?

**Comment by sonj2** [comment]
Filling out every field manually seems to cause the same exact crash. I quite literally copied the weapontweakdata code for chinchilla, then modified it for jeb and started fixing 1 crash issue at a time. Then I hit a wall at the same crash I got from the cloning attempt.

**Comment by sonj2** [comment]
```
Application has crashed: C++ exception
[string "lib/managers/upgradesmanager.lua"]:565: attempt to index local 'upgrade' (a nil value)



SCRIPT STACK

_setup_weapons() lib/managers/blackmarketmanager.lua:296
_setup() lib/managers/blackmarketmanager.lua:54
init() lib/managers/blackmarketmanager.lua:18
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:382
init_managers() @mods/base/req/core/Hooks.lua:260
init_managers() lib/setups/menusetup.lua:273
core/lib/setups/coresetup.lua:382


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name   
```

**Comment by sonj2** [comment]
Well, with more attempts, I think I can nail the gun not working down to that the upgrademanager.lua is unable to find the tweak_data.upgrades.definitions[upgrade_id] for Jeb. Resmod already has and entry for Jeb in upgradestweakdata; I wonder if the vanilla weapons or Beardlib added weapons have some other code not part of the lua scripts...

**Comment by EvilBobarino** [comment]
just set it up using beardlib 
IF syncing is figured out down the line we can swap it over but we can live without for now

**Comment by sonj2** [comment]
Jeb is alive on dev branch; after like 1 and a half years since the creation of this issue.
