### ISSUE TITLE
Unknown cause for access violations on death sentence lobbies as client

### ISSUE THREAD

**Issue by AnadorableStrayCat** [payday-restoration/restoration-mod#430]
When joining someone's death sentence lobby, the game runs smoothly during stealth gameplay, and in loud control phase. As soon as anticipation begins and all the units start spawning in, the entire game crashes due to an access violation.

**Comment by EssCee** [comment]
Please post your crash.txt, and if possible, you're more likely to get a response on our Discord for support. 

https://discord.gg/YmQkDyY

**Comment by AnadorableStrayCat** [comment]
[crash.txt](https://github.com/payday-restoration/restoration-mod/files/9528162/crash.txt)
