### ISSUE TITLE
Assault Tape Text Exit Animation Broken

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#52]
On the assault tape, we had restored functionality from PD2's alpha where the text would already by on the tape and animate into the screen and out with it, but currently, it does the normal PD2 text functionality.  A recent change may have broken it.

**Comment by SOMNUSNOVUS** [comment]
Update on this report:

Text functionality still remains the same.  Working on getting a reference GIF to illustrate the issue.

**Comment by SOMNUSNOVUS** [comment]
Apologies, a versioning problem had me misdiagnose, this issue is actually _partially_ fixed.  The text animation for assault beginning is now working correctly.

The animation for assault end is still broken, currently -- at the moment, it merely vanishes when the assault ends, when it should persist until the tape is fully out of the screen.

**Comment by steam-test1** [comment]
Does it look like how the casing ticker animation closes?

**Comment by SOMNUSNOVUS** [comment]
No.  It should be like the intro anim, but in... reverse.

I'm surprised you still had the old anim code for our temporary casing mode ticker, though.  It should ideally be using the same animations as the normal assault tape, though.  Perhaps later on, we can have our V4.0 animations as a setting.

**Comment by SOMNUSNOVUS** [comment]
Issue persists.

I think we had it working fine at one point, but after I took a half-year break from PD2, the exit anim stopped working?

Here's how roughly it should look for intro/exit (pulled from alpha footage)
https://cdn.discordapp.com/attachments/335575043096576000/589257775117369382/assault.gif
https://cdn.discordapp.com/attachments/335575043096576000/589257804834013184/reverse.gif

**Comment by SOMNUSNOVUS** [comment]
Updated this issue.

Recently remembered that the Captain buff icons aren't working with the tape/old alpha indicator anymore.  I know it broke at some point after we initially implemented it, but it never got fixed.

Additionally, the assault end animation for the _vanilla_ assault indicator is busted too, instead of the box closing, it just.. vanishes.  Is this our fault???

**Comment by steam-test1** [comment]
The exit animation seems to have been broken in the beta source code, as I tried tweaking and loading different version of _animate_assault and _animate_text and exit animation didn't play like in the alpha
In the beta source code in function _end_assault there is a commented out line self._exiting = true
Maybe the old 4.0 animations can be modify to match the alpha animations

**Comment by SOMNUSNOVUS** [comment]
This is weird.  Akcel had gotten the animation restored long ago -- some update (either the settings update to our code, or a game update) had broken it.  

I wouldn't worry too much on this at the moment -- I can try to contact Akcel for opinion on it.

**Comment by SOMNUSNOVUS** [comment]
Ultimately, it needs to just look like the entry anim, but.. in reverse.  The tape itself is working fine -- text just decides to vanish.

**Comment by SOMNUSNOVUS** [comment]
This issue persists.  Unless someone fixed it without me knowing?

Re-opening until we confirm the issues with it have been solved.

**Comment by steam-test1** [comment]
Closing as it's been fixed
