### ISSUE TITLE
Restoration lacks SuperBLT and package functionality

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#53]
Restoration uses a mess of code throughout different BeardLIB/BLT versions, and we can't get SuperBLT working properly with it (as the addition of supermod.xml simply crashes the game).

Anyone who can -- upgrade _all_ of our systems to be on SuperBLT alone, and to use the package system.  We can handle hooking up the necessary packages to different functionality after that, but at a baseline, we can't viably swap our whole system to SuperBLT.

**Comment by steam-test1** [comment]
Update the release version of SuperBLT lua no longer crashes on startup
