### ISSUE TITLE
Buying Mask Materials with Coins crashes

### ISSUE THREAD

**Issue by Colotov-Mocktail** [payday-restoration/restoration-mod#586]
Application has crashed: C++ exception
mods/restoration-mod/lua/sc/managers/blackmarketgui.lua:7443: attempt to perform arithmetic on field 'amount' (a nil value)

SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:86
on_create_func() @mods/restoration-mod/lua/sc/managers/blackmarketgui.lua:6951
init() lib/managers/menu/blackmarketgui.lua:157
new() core/lib/utils/coreclass.lua:35
_setup() @mods/restoration-mod/lua/sc/managers/blackmarketgui.lua:1223
reload() lib/managers/menu/blackmarketgui.lua:15559
_ReloadBlackMarket() @mods/restoration-mod/lua/sc/managers/blackmarketgui.lua:7229
callback_func() @mods/restoration-mod/lua/sc/managers/blackmarketgui.lua:7411
button_pressed() lib/managers/dialogs/dialog.lua:61
button_pressed() lib/managers/dialogs/genericdialog.lua:375
button_pressed_callback() lib/managers/dialogs/genericdialog.lua:371
mouse_press() lib/managers/dialogs/genericdialog.lua:123
lib/managers/mousepointermanager.lua:345

**Comment by EssCee** [comment]
Fixed some time ago.
