### ISSUE TITLE
Add back Day Rate and failure XP

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#59]
As title says.  I can't figure out what file is handling both of these.  If anyone figures it out, make a fork request/push to mod, they'll be active in overhaul only.

**Comment by SOMNUSNOVUS** [comment]
Still unsure what's causing these not to work -- the tweak data entry for failure XP doesn't seem to work when modified to pay out above 0, is there something else preventing day rate cash & failure XP?

**Comment by steam-test1** [comment]
Try looking at https://github.com/steam-test1/old-lua-repo/blob/8736dd27b5be657f9591ed68847c917eb02a2c9a/lib/managers/moneymanager.lua
It may contain the code to restore it

**Comment by SOMNUSNOVUS** [comment]
No dice, I restored a few things in this file, but no change on ingame functionality.

**Comment by steam-test1** [comment]
Could you share the code that you have?
