### ISSUE TITLE
Crashing on game start

### ISSUE THREAD

**Issue by kakahost** [payday-restoration/restoration-mod#609]
Application has crashed: C++ exception
...on-mod-gold/lua/sc/tweak_data/weaponfactorytweakdata.lua:9: attempt to index local 'part_data' (a nil value)

SCRIPT STACK

original() lib/tweak_data/weaponfactorytweakdata.lua:624
init() @mods/base/req/core/Hooks.lua:260
new() core/lib/utils/coreclass.lua:35
_init_data_player_weapons() lib/tweak_data/weapontweakdata.lua:7839
init() lib/tweak_data/weapontweakdata.lua:44
new() core/lib/utils/coreclass.lua:35
init() lib/tweak_data/tweakdata.lua:545
new() core/lib/utils/coreclass.lua:35
lib/tweak_data/tweakdata.lua:3639
require() =[C]
require() @mods/base/base.lua:193
lib/setups/setup.lua:45
require() =[C]
require() @mods/base/base.lua:193
lib/setups/menusetup.lua:1
require() =[C]
require() @mods/base/base.lua:193
lib/entry.lua:13
require() =[C]
require() @mods/base/base.lua:193
core/lib/coreentry.lua:19

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main
Script stack:
                    original()  lib/tweak_data/weaponfactorytweakdata.lua:624       
                        init()  @mods/base/req/core/Hooks.lua:260                   
                         new()  core/lib/utils/coreclass.lua:35                     
   _init_data_player_weapons()  lib/tweak_data/weapontweakdata.lua:7839             
                        init()  lib/tweak_data/weapontweakdata.lua:44               
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  lib/tweak_data/tweakdata.lua:545                    
                         new()  core/lib/utils/coreclass.lua:35                     
                                lib/tweak_data/tweakdata.lua:3639                   
                     require()                                                      
                          =[C]  require()                                           
                                @mods/base/base.lua:193                             
       lib/setups/setup.lua:45  require()                                           
                          =[C]  require()                                           
       @mods/base/base.lua:193                                                      
    lib/setups/menusetup.lua:1  require()                                           
                                =[C]                                                
                     require()                                                      
       @mods/base/base.lua:193  lib/entry.lua:13                                    
                     require()  =[C]                                                
                     require()  @mods/base/base.lua:193                             
                                core/lib/coreentry.lua:19                           

-------------------------------

System information:
	Application version : 1.143.243
	CPU : Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 Ti / nvldumd.dll[32.0.15.5599]
	Language : english
	Memory :     16308MB 896KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Динамики (High Definition Audio Device))

**Comment by EssCee** [comment]
Unable to reproduce on current gold and dev, please verify the integrity of your Resmod installation. Consider using a git client like GitHub Desktop for easy installing and updating, as well as minimizing the chance of a bad install.
