### ISSUE TITLE
Cook Off Crash

### ISSUE THREAD

**Issue by Chaoxufurwa** [payday-restoration/restoration-mod#611]
I keep encountering this specific crash on Cook Off. No clue what the cause is, besides maybe being related to Cop movement logic? One time it happened when I killed a taser on top of the shed nearest to the pickup truck. Not sure if it would happen on Rats Day one or not.

[crash.txt](https://github.com/user-attachments/files/17270874/crash.txt)

**Comment by EssCee** [comment]
While GitHub issues are the typically spot to troubleshoot issues, you'll get more immediate troubleshooting in the Discord channel of the same name.

https://discord.gg/YmQkDyY
