### ISSUE TITLE
Load assets using custom packages

### ISSUE THREAD

**Issue by steam-test1** [payday-restoration/restoration-mod#63]
Included only changed files so you don't have to download the whole branch
https://github.com/steam-test1/restoration-mod/blob/dev/restoration%20custom%20packages.zip?raw=true
The following uses custom packages to load the assets
Currently there is only 2(One for SC assets and other for HUD and map assets)
All the overhaul assets will only load if you have the overhaul active at startup
This should allow HUD only users to get faster loading times

**Comment by SOMNUSNOVUS** [comment]
Thank you very much!

I'll be merging it into the dev branch when I'm home, or someone else will in my absence.  We were planning to get started on packages today/this week anyways, so this helps.

**Comment by SOMNUSNOVUS** [comment]
Implemented, works as intended.
