### ISSUE TITLE
Dodge Meter Conflicts w/ Other HUD Mods

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#64]
Title.

We're already slowly trying to fix any visual bugs w/ the meter, but we're strapped for time to dedicate to it, so I'm sticking this issue up here for anyone willing to try and make it work better.

Ideally, we want a new HUD element for it that won't conflict with other mods (most likely), and have a better visual appearance, its current setup within HUDTemp is, well, temporary for testing the system.

**Comment by SOMNUSNOVUS** [comment]
Issue partially resolved -- no longer causes conflict with ResHUD itself.

Still needing to get around to making a new HUD element for the dodge meter instead of relying on HUDTemp -- stamina bar appearance is ugly, and there's almost surely a better place to put the meter, and also need to make it not conflict with other mods doing things to HUDTemp.

**Comment by SOMNUSNOVUS** [comment]
Rolled back to earlier commit -- the dodge meter now uh, crashes.  Uh oh.

Running on vanilla HUD, any idea of cause?

**Comment by SOMNUSNOVUS** [comment]
Update on this report:

I'm stupid and my reading comprehension finally kicked in.

Line 108 ( self:dodge_init() ) needs to be called even if ResHUD isn't on.  Ravi coded this ResHUD's HUDTemp, when they really should have created in a new file, but whatever.

I haven't touched code seriously in over a year, so thank you for bearing with me on my panicked-stupidity.

**Comment by steam-test1** [comment]
When does it need to display?

**Comment by SOMNUSNOVUS** [comment]
Sorry, sorry.  I DIY fixed it now that I remember how lua works -- just made a copy of the HUDTemp init function to be posthook'd if the main HUD _isn't_ on.  Gets the job done.  Feel free to make it prettier if you want?

**Comment by SOMNUSNOVUS** [comment]
Additional _tiny_ issue I won't try to fix myself this time:

Bag text with ResHUD on does.. this?

https://cdn.discordapp.com/attachments/335573583881437185/592755056831627301/unknown.png

The formatting seems to.. break, for some reason.  The code for the bag stuff seems 1-1 to the pre-dodge meter one, so I dunno.

**Comment by SOMNUSNOVUS** [comment]
Issue resolved.  <3
