### ISSUE TITLE
Old menu buttons have misalignment in some menus

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#65]
Title.

Currently, I only have the pause renderer variation of these menus implemented, but some menus (like the color picker menu for reshud) have alignment issues.

This would be an easy fix if I knew the _name of the colors menu node._  If anyone can find out or knows who to grab this information, lemme know.

**Comment by steam-test1** [comment]
The color picker node is RestorationModColorsOptionsNode

**Comment by SOMNUSNOVUS** [comment]
Issue resolved, thank you very much.  <3
