### ISSUE TITLE
Custom packages causing odd issues with clients

### ISSUE THREAD

**Issue by Teacyn** [payday-restoration/restoration-mod#68]
Heists with custom packages (such as murky heists) often disconnect clients when reaching the loadout screen. This seems completely random, however loading a heist with custom packages before one without seems to more consistently trigger the disconnect. 

Clients sometimes don't disconnect at all, sometimes they disconnect but can immediately rejoin, and sometimes they disconnect and then can't rejoin (immediately get "Failed joining lobby" if they try to).

**Comment by EvilBobarino** [comment]
Bug still seems to occur with new network changes

**Comment by SOMNUSNOVUS** [comment]
Does this issue persist after the BeardLib update?

**Comment by steam-test1** [comment]
Does this happen on heists without custom outfits?
