### ISSUE TITLE
Fix/replace odd string when leveling every 10 levels

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#74]
The game still rewards the "2 more skill points!" event every 10 levels, but since of our 100 point cap, this is now... "0 more skill points!"

Suggested courses of action:

- Remove/Update this string in the overhaul so it's not weird
- Make leveling up every 10 levels award continental coins/cash/something???

**Comment by Ravicale** [comment]
Going to be going over the level_tree in upgrades tweakdata for progression stuff tonight. My initial hunch is that removing the 'rep_upgradex' instances from the array will fix the issue.

**Comment by steam-test1** [comment]
The string been replaced
