### ISSUE TITLE
Old Contours

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#81]
We've tried for a long time to get PD:TH styled contours back into the game, but to no avail.

This is seemingly impossible with our expertise -- old contours appear to be part of the shader library, and we can't exactly deconstruct the shaders and rebuild them.

If anyone has anything to contribute regarding this, it will most likely be implemented.

**Comment by steam-test1** [comment]
This is possible, but requires a bundle mod and can't be included until SuperBLT gets the ability to load shaders
