### ISSUE TITLE
Revert restart function to where it crashed the game

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [payday-restoration/restoration-mod#85]
Title.

When it restarts the game normally & not via a crash, it can do -weird- things with the game.  I had turned off the overhaul and several overhaul values were still active when restarting the game, which should not happen.

**Comment by SOMNUSNOVUS** [comment]
This runs a risk of corrupting user saves in some way.  Would recommend prompt addressing of this.

**Comment by SOMNUSNOVUS** [comment]
Issue resolved.  <3

**Comment by steam-test1** [comment]
Should the change be pushed to the gold version?

**Comment by SOMNUSNOVUS** [comment]
Yes, ASAP.
