### ISSUE TITLE
Large framedrops mid hesit

### ISSUE THREAD

**Issue by EvilBobarino** [payday-restoration/restoration-mod#94]
From testing in bank heist (occurs on other heists too) the games framerate drops significantly around 5 minutes into a heist. This issue has only popped up very recently around when we started testing packages and superblt loading.

**Comment by steam-test1** [comment]
Try testing on Boiling Point with the latest commit
If that doesn't fix it, then ia Beardlib issue can be created

**Comment by EvilBobarino** [comment]
will do

**Comment by EvilBobarino** [comment]
the framerate was fine until i restarted the heist. the restart dropped the frames hhhh

**Comment by steam-test1** [comment]
Try with the latest commit
If that doesn't fix it, then a Beardlib issue can be created

**Comment by Teacyn** [comment]
Seems to still happen. It's worth noting that we've gotten conflicting results about this. Several team members have reported major FPS drops (one of whom became unable to play the game they were so bad), but I have personally not experienced any FPS drops at all.

**Comment by SOMNUSNOVUS** [comment]
I suspect it maybe isn't a Beardlib issue, but some change we've performed over the past few days?  From the sounds of things, it wasn't happening before.

**Comment by steam-test1** [comment]
Try with the latest commit

**Comment by EvilBobarino** [comment]
i think that worked

**Comment by Teacyn** [comment]
conversly I'm now getting _massive_ performance drops. On big Bank in stealth I was very frequently dropping from 90+ down to sub-20 FPS and stuttering like crazy.

**Comment by steam-test1** [comment]
If that worked could someone make a request for Beardlib to only unload custom packages when you finished playing the level
That should solve the issue

**Comment by EvilBobarino** [comment]
issue was with the obstacle tactic and has been fixed
